{{- if .Values.createClusterRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: daas-role
rules:
- apiGroups: [ "", "apps", "extensions", "networking.k8s.io", batch]
  resources:
  - services
  - pods
  - namespaces
  - secrets
  - deployments
  - configmaps
  - ingresses
  - persistentvolumeclaims
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
{{- end }}
