apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      serviceAccountName: {{.Values.sa}}
      containers:
      - name: server
        image: javaspring-demoapp:1.0
        env:
        - name: namespace
          value: {{.Release.Namespace}}
        - name: spring.datasource.url
          value: jdbc:postgresql://{{.Release.Name }}-postgresql.{{.Release.Namespace}}.svc.cluster.local:5432/daas-db
        - name: spring.datasource.username
          value: {{.Values.dbuser}}
        - name: spring.datasource.password
          value: {{.Values.dbpass}}
        - name: domainsuffix
          value: {{.Values.domainsuffix}}
        imagePullPolicy: Never     
        resources:
        ports:
          - containerPort: 8081

         