apiVersion: v2
appVersion: v10.1
description: A Helm chart for DaaS
name: daas-helmchart
version: 1.0

dependencies:
- name: postgresql
  version: 9.8.5
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.install
