
nameOverride: "daas"
fullnameOverride: "daas"


domainsuffix: test.daidemo.com
dbuser: daas
dbpass: daas
sa: daas
createClusterRole: true

## Ref: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/README.md
## Install postgresql chart. If you have an existing database deployment, set 'install' to 'false'.
postgresql:
  install: true
  postgresqlUsername: postgres
  postgresqlPassword: ""
  postgresqlExtendedConf:
    listenAddresses: "'*'"
    maxConnections: "500"
  initdbScriptsSecret: postgresql-init-sql
  #initdbScriptsConfigMap: initdb-configmap
  service:
    port: 5432
  persistence:
    enabled: true
    storageClass: custom
    size: 8Gi
    existingClaim:
  resources: {}
  #  requests:
  #    memory: "1Gi"
  #    cpu: "250m"
  #  limits:
  #    memory: "2Gi"
  #    cpu: "1"
  nodeSelector: {}
  affinity: {}
  tolerations: []


